Asta 32
asta-design-br/asta pull request #10
Opened 2023-03-16 19:27 UTC by danirioss

things that I've done:

address table (need to run migration)
address model
address prepared to be associated with model and event (polimorphism)
address validations

2023-03-16 19:37 UTC, jucaesmanhoto reviewed
Acredito que não esteja no card do Jira, mas seria interessante que o campo :state tivesse uma validação para ter apenas 2 caracteres. O que acha?

2023-03-17 11:37 UTC, edcolen requested changes

2023-03-17 11:37 UTC, edcolen commented on app/models/address.rb
> +  belongs_to :addressable_id, polymorphic: true
Aqui seria melhor `belongs_to :addressable, polymorphic: true`, para que o método criado seja realmente addressable.

2023-03-17 11:37 UTC, edcolen commented on app/models/user.rb
> +  has_one :address, as: :addressable
Fiquei na dúvida se usaremos somente um endereço por objeto ou mais de um.
Eu iria com o `has_many`. O que acha @jucaesmanhoto ?

2023-03-17 11:37 UTC, edcolen commented on db/migrate/20230316180651_create_addresses.rb
> +      t.references :addressable, polymorphic: true, null: false
Aqui eu acrescentaria `index: true`, para já irmos indexando e melhorando a performance da db.

2023-03-17 20:35 UTC, jucaesmanhoto commented on app/models/user.rb
> +  has_one :address, as: :addressable
@danirioss acho que realmente não tem necessidade de limitar apenas um endereço por usuário... Vamos com o has_many :)

2023-03-21 15:29 UTC, edcolen approved these changes

2023-03-21 22:14 UTC, merged