Asta 18
asta-design-br/asta pull request #22
Opened 2023-03-28 00:28 UTC by nathpi

Criação do footer

2023-03-28 01:32 UTC, jucaesmanhoto requested changes
Tá quase perfeita @nathpi 
Mas vou aproveitar que ficou uma linha vazia sobrando e vou pedir pra vc acrescentar os links corretos nos ícones:
https://twitter.com/astadesign_br
https://www.instagram.com/asta.design.br/

2023-03-28 01:32 UTC, jucaesmanhoto commented on app/views/pages/home.html.erb
> +
Essa linha nova tá sobrando. Não faria muita diferença deixar ou tirar. Mas é sempre bom evitar ter arquivos desnecessários numa PR. Por enquanto as PRs estão pequenas, mas é interessante irmos nos habituando, pq mais pra frente elas vão tender a ficar bem maiores, e aí cada arquivo a menos é um alívio. :)

2023-03-28 15:22 UTC, nathpi commented on app/views/pages/home.html.erb
> +
Obrigada pelo toque @jucaesmanhoto !
Vou ajustar.

2023-03-29 05:01 UTC, jucaesmanhoto approved these changes
Ficou perfeito @nathpi !!! :)

2023-03-29 13:40 UTC, nicolasenne approved these changes
10/10 arrasou!

2023-03-29 16:03 UTC, merged