Asta 24
asta-design-br/asta pull request #25
Opened 2023-04-01 00:23 UTC by afonsoggarcia

2023-04-01 12:44 UTC, jucaesmanhoto requested changes

2023-04-01 12:44 UTC, jucaesmanhoto commented on app/models/auction.rb
> +  def deadline_after_now_before_start_time
@afonsoggarcia Pensei algumas sugestões aqui pra deixar seu código mais "limpo" e mais fácil de lermos depois...
Veja se vc gosta da ideia:
- colocar cada uma das condicionais em uma variável. Ficaria mais ou menos assim:
```
is_before_event_start = product.present? && deadeline < product.event.start_time
is_after_now = deadline > DateTime.now
```
assim, o seu "if" ficaria mais legível
```
return if deadline.present? && is_after_now && is_before_event_start
```

- O nome do método talvez fosse legal a gente usar algo como validate_deadline ou então deadline_custom_validate... Assim, se depois colocarmos outros métodos no modelo, fica mais fácil de achar o que está validando o deadline.

2023-04-01 12:44 UTC, jucaesmanhoto commented on spec/models/bid_spec.rb
Esse arquivo pode ser deletado se não tiver nenhum teste. Se não ele vai sempre aparecer como algo pendente.

2023-04-03 18:26 UTC, afonsoggarcia commented on spec/models/bid_spec.rb
Putz, eu acabei de atualizar o código alterando a condicional da Auction e apaguei a model e a factory de Bid... agora que vim aqui submeter pra você que vi esse comentário.
Mas então pra se fazer a Bid tem que ser designer e/ou producer_designer... certo?

2023-04-03 19:16 UTC, jucaesmanhoto commented on spec/models/bid_spec.rb
Na verdade, nos role do user que fiazer a bid precisa conter a role 'designer'. E pra criar um evento, nas role do user precisa conter a role 'producer'.

2023-04-04 00:32 UTC, jucaesmanhoto requested changes

2023-04-04 00:32 UTC, jucaesmanhoto commented on app/models/auction.rb
> +  validates :deadline, :product, presence: true
deixar uma linha em branco para separar os relacionamentos das validação

2023-04-04 00:32 UTC, jucaesmanhoto commented on app/models/product.rb
Adicionar um 
has_many :bids, through: :auctions

2023-04-04 00:32 UTC, jucaesmanhoto commented on db/seeds.rb
> +puts 'destroying every Bid'
Corrigir o puts para 'destroying every Auction'

2023-04-04 00:32 UTC, jucaesmanhoto commented on db/seeds.rb
> +Bid.create!(
Um producer não pode dar lances

2023-04-04 00:32 UTC, jucaesmanhoto commented on app/models/auction.rb
> +    is_before_event_start = product.present? && deadline < product.event.start_time
Corrigir a validação para passar nos testes

2023-04-04 02:07 UTC, jucaesmanhoto approved these changes

2023-04-04 02:07 UTC, merged