Product model seed
asta-design-br/asta pull request #28
Opened 2023-04-03 18:32 UTC by danirioss

tinha esquecido de criar o seed do model de Product mas aí esta afinal

ps: deletei o Event.destroy_all e o Product.destroy_all no arquivo de seed

por que Product está associado ao Event que está associado ao User - ambos com o dependent destroy

então se entendi bem, quando deletarmos os Users criados consequentemente os Events e os Products tb serão deletados, certo? (pelo menos quando rodei o seed aqui funcionou)

2023-04-04 21:11 UTC, jucaesmanhoto requested changes

2023-04-04 21:11 UTC, jucaesmanhoto commented on app/models/event.rb
>    validates :title, :description, :start_time, :end_time, presence: true
acredito que precise de uma validação aqui de presence do User tbm.

2023-04-04 21:11 UTC, jucaesmanhoto commented on app/models/role.rb
>    validates :name, inclusion: { in: %w[designer producer], message: '%<value> is not a valid role.' }
se deixar uma linha vazia de separação, fica mais fácil depois de saber onde terminam os relacionamentos e onde começam as validações

2023-04-04 21:11 UTC, jucaesmanhoto commented on db/seeds.rb
Não vejo muita necessidade de deixar códigos comentados nesse caso. Acho melhor apagar. Se precisarmos deles novamente, ou escrevemos de novo, ou buscamos no histórico aqui do github pra fazer um copy/paste

2023-04-05 00:38 UTC, danirioss commented on db/seeds.rb
a verdade verdadeira é que eu esqueci de apagar

2023-04-05 02:10 UTC, danirioss commented on app/models/event.rb
>    validates :title, :description, :start_time, :end_time, presence: true
abri outra branch pra solucionar este BO aqui. as outras modificações que vc pediu abaixo eu fiz neste PR mesmo

2023-04-05 02:24 UTC, jucaesmanhoto approved these changes

2023-04-05 17:34 UTC, merged