Asta 19
asta-design-br/asta pull request #5
Opened 2023-03-09 22:44 UTC by danirioss

added columns to user
user validations done

2023-03-09 23:49 UTC, jucaesmanhoto reviewed
Só um pequeno ajuste nas validações pra ficar mais fácil de identificar as validações customizadas.

2023-03-09 23:49 UTC, jucaesmanhoto commented on app/models/user.rb
> +  validate :check_full_name, :check_username, :check_document
@danirioss separa o validate dos validates pra ficar mais claro quais são as validações do ActiveRecords e quais são customizadas.

2023-03-10 18:17 UTC, edcolen commented
Como estamos adicionando atributos ao model de User, seria interessante já acrescentarmos os strong params do Devise ao ApplicationController, bem como os novos campos nos forms de criação e edição de conta.

2023-03-10 18:27 UTC, edcolen requested changes
Como estamos adicionando atributos ao model de User, seria interessante já acrescentarmos os strong params do Devise ao ApplicationController, bem como os novos campos nos forms de criação e edição de conta.

2023-03-13 21:24 UTC, edcolen requested changes
Os params para a criação de conta foram feitos corretamente. Eu aproveitei para adicionar também para a atualização da conta.

Agora, só para ficar redondinho, falta só acrescentar esses campos novos nos forms de registration (new e edit), para que o usuário consiga colocar essas informações.

2023-03-14 12:37 UTC, edcolen requested changes
Fechando os sorvetes dos formulários e vendo se não há outros erros de sintaxe, acho que finaliza.

2023-03-14 12:37 UTC, edcolen commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.input :full_name,
Acredito que podemos ficar sem as hints por enquanto, acho que não precisamos esclarecer nada para o usuário nessa parte.
Veja também os "sorvetes" que estão faltando fechar nesses campos.

2023-03-14 12:37 UTC, edcolen commented on app/views/devise/registrations/new.html.erb
> +                required: true,
Faltou fechar o sorvete do profile.

2023-03-16 16:07 UTC, danirioss commented on app/views/devise/registrations/new.html.erb
> +                required: true,
ops. sorvetões devidamente fechados. paginas de edit e new de registration user testadas. tb adicionei os devidos links nas devidas homes para facilitar o teste destas funcionalidades. agora eu acho que vai!

2023-03-17 11:31 UTC, edcolen approved these changes

2023-03-20 23:28 UTC, merged