Active Storage migration done
asta-design-br/asta pull request #6
Opened 2023-03-09 23:09 UTC by afonsoggarcia

2023-03-09 23:51 UTC, jucaesmanhoto reviewed
@afonsoggarcia Aparentemente está ok. Mas seria bom o @edcolen dar uma olhada tbm antes de fazermos o merge.

2023-03-10 18:21 UTC, edcolen requested changes
Aparentemente tudo certo.
Só mesmo aquela linha do model de User que ainda não tem utilidade.

2023-03-10 18:21 UTC, edcolen commented on app/models/user.rb
> +  has_one_attached :avatar
Ainda não temos a lógica para acrescentar o avatar, então essa linha fica desnecessária.

2023-03-10 19:06 UTC, afonsoggarcia commented on app/models/user.rb
> +  has_one_attached :avatar
Removi a linha

2023-03-10 19:43 UTC, edcolen approved these changes

2023-03-10 21:42 UTC, merged